# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Research"
  url = "#projects"
  weight = 2

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 3
  
[[main]]
  name = "WorkingPapers"
  url = "workingpapers/"
  weight = 4

[[main]]
  name = "Presentations"
  url = "#talks"
  weight = 5

[[main]]
  name = "Teaching"
  url = "courses/"
  weight = 6

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 7
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "Lee_CV_Oct2020v2.pdf"
    weight = 9
